name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: Far-Beyond-Pulsar/Pulsar-Native
        ref: 5841880a3a2a371ec4975d601c72188835b48849
        submodules: recursive
        path: pulsar
    - uses: actions/checkout@v4
      with:
        path: pulsar/crates/ui/wgpui-component
    - name: Build
      run: cargo build -p ui --verbose
      working-directory: pulsar
    - name: Run tests
      run: cargo test -p ui --verbose
      working-directory: pulsar
